### ISSUE TITLE
Configurable Interval Setting, by Input

### ISSUE THREAD

**Issue by echtelerp** [ArnaudRinquin/node-red-contrib-interval#1]
Hi Arnaud, 
I was wondering, if it is possible, to set the Interval by input. 
For example: 
I have a slider on my node Red Dashbord. 
I now want to Adjust the Interval by that slider. 
Use case is that i periodically want to inject. but all done by an Input node.

**Comment by domnpp** [comment]
Hi echtelerp,
is this still required? I have forked the project, could add the feature

**Comment by echtelerp** [comment]
Hi domenn,
Of course. Would still be a nice feature.

**Comment by domnpp** [comment]
Pull request submitted. In the meantime, you can use my fork. Simply git clone into your node-modules directory.
https://github.com/domenn/node-red-contrib-interval

**Comment by domnpp** [comment]
Published modified version as different node. Since I need modifications for my purposes anyway.
https://www.npmjs.com/package/node-red-contrib-configurable-interval
